/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { JsonDocsComponent } from "../docs-data";
import { MatchResults, RouterHistory } from "@stencil/router";
export namespace Components {
    interface AppHeader {
    }
    interface AppLogo {
    }
    interface AppNav {
    }
    interface AppRoot {
    }
    interface CodeBlock {
        "code": string;
        "component": JsonDocsComponent;
    }
    interface ComponentSidebar {
    }
    interface DocUsage {
        "usage": string;
    }
    interface HlCode {
        "code"?: string;
        "language"?: string;
    }
    interface PageComponents {
        /**
          * url params matcher
         */
        "match": MatchResults;
    }
    interface PageHelperClasses {
    }
    interface PageHome {
    }
    interface PageNotfound {
    }
    interface PageStandard {
        "history": RouterHistory;
        /**
          * url params matcher
         */
        "match": MatchResults;
    }
    interface ThemeSetter {
    }
    interface UtterancesDiv {
        "async"?: boolean;
        "crossorigin"?: string;
        "issueTerm"?: string;
        "label"?: string;
        "repo": string;
        "theme"?: string;
    }
}
declare global {
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppLogoElement extends Components.AppLogo, HTMLStencilElement {
    }
    var HTMLAppLogoElement: {
        prototype: HTMLAppLogoElement;
        new (): HTMLAppLogoElement;
    };
    interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {
    }
    var HTMLAppNavElement: {
        prototype: HTMLAppNavElement;
        new (): HTMLAppNavElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCodeBlockElement extends Components.CodeBlock, HTMLStencilElement {
    }
    var HTMLCodeBlockElement: {
        prototype: HTMLCodeBlockElement;
        new (): HTMLCodeBlockElement;
    };
    interface HTMLComponentSidebarElement extends Components.ComponentSidebar, HTMLStencilElement {
    }
    var HTMLComponentSidebarElement: {
        prototype: HTMLComponentSidebarElement;
        new (): HTMLComponentSidebarElement;
    };
    interface HTMLDocUsageElement extends Components.DocUsage, HTMLStencilElement {
    }
    var HTMLDocUsageElement: {
        prototype: HTMLDocUsageElement;
        new (): HTMLDocUsageElement;
    };
    interface HTMLHlCodeElement extends Components.HlCode, HTMLStencilElement {
    }
    var HTMLHlCodeElement: {
        prototype: HTMLHlCodeElement;
        new (): HTMLHlCodeElement;
    };
    interface HTMLPageComponentsElement extends Components.PageComponents, HTMLStencilElement {
    }
    var HTMLPageComponentsElement: {
        prototype: HTMLPageComponentsElement;
        new (): HTMLPageComponentsElement;
    };
    interface HTMLPageHelperClassesElement extends Components.PageHelperClasses, HTMLStencilElement {
    }
    var HTMLPageHelperClassesElement: {
        prototype: HTMLPageHelperClassesElement;
        new (): HTMLPageHelperClassesElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageNotfoundElement extends Components.PageNotfound, HTMLStencilElement {
    }
    var HTMLPageNotfoundElement: {
        prototype: HTMLPageNotfoundElement;
        new (): HTMLPageNotfoundElement;
    };
    interface HTMLPageStandardElement extends Components.PageStandard, HTMLStencilElement {
    }
    var HTMLPageStandardElement: {
        prototype: HTMLPageStandardElement;
        new (): HTMLPageStandardElement;
    };
    interface HTMLThemeSetterElement extends Components.ThemeSetter, HTMLStencilElement {
    }
    var HTMLThemeSetterElement: {
        prototype: HTMLThemeSetterElement;
        new (): HTMLThemeSetterElement;
    };
    interface HTMLUtterancesDivElement extends Components.UtterancesDiv, HTMLStencilElement {
    }
    var HTMLUtterancesDivElement: {
        prototype: HTMLUtterancesDivElement;
        new (): HTMLUtterancesDivElement;
    };
    interface HTMLElementTagNameMap {
        "app-header": HTMLAppHeaderElement;
        "app-logo": HTMLAppLogoElement;
        "app-nav": HTMLAppNavElement;
        "app-root": HTMLAppRootElement;
        "code-block": HTMLCodeBlockElement;
        "component-sidebar": HTMLComponentSidebarElement;
        "doc-usage": HTMLDocUsageElement;
        "hl-code": HTMLHlCodeElement;
        "page-components": HTMLPageComponentsElement;
        "page-helper-classes": HTMLPageHelperClassesElement;
        "page-home": HTMLPageHomeElement;
        "page-notfound": HTMLPageNotfoundElement;
        "page-standard": HTMLPageStandardElement;
        "theme-setter": HTMLThemeSetterElement;
        "utterances-div": HTMLUtterancesDivElement;
    }
}
declare namespace LocalJSX {
    interface AppHeader {
    }
    interface AppLogo {
    }
    interface AppNav {
    }
    interface AppRoot {
    }
    interface CodeBlock {
        "code"?: string;
        "component"?: JsonDocsComponent;
    }
    interface ComponentSidebar {
    }
    interface DocUsage {
        "usage"?: string;
    }
    interface HlCode {
        "code"?: string;
        "language"?: string;
    }
    interface PageComponents {
        /**
          * url params matcher
         */
        "match"?: MatchResults;
    }
    interface PageHelperClasses {
    }
    interface PageHome {
    }
    interface PageNotfound {
    }
    interface PageStandard {
        "history"?: RouterHistory;
        /**
          * url params matcher
         */
        "match"?: MatchResults;
    }
    interface ThemeSetter {
        "onThemeChanged"?: (event: CustomEvent<boolean>) => void;
    }
    interface UtterancesDiv {
        "async"?: boolean;
        "crossorigin"?: string;
        "issueTerm"?: string;
        "label"?: string;
        "repo"?: string;
        "theme"?: string;
    }
    interface IntrinsicElements {
        "app-header": AppHeader;
        "app-logo": AppLogo;
        "app-nav": AppNav;
        "app-root": AppRoot;
        "code-block": CodeBlock;
        "component-sidebar": ComponentSidebar;
        "doc-usage": DocUsage;
        "hl-code": HlCode;
        "page-components": PageComponents;
        "page-helper-classes": PageHelperClasses;
        "page-home": PageHome;
        "page-notfound": PageNotfound;
        "page-standard": PageStandard;
        "theme-setter": ThemeSetter;
        "utterances-div": UtterancesDiv;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-logo": LocalJSX.AppLogo & JSXBase.HTMLAttributes<HTMLAppLogoElement>;
            "app-nav": LocalJSX.AppNav & JSXBase.HTMLAttributes<HTMLAppNavElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "code-block": LocalJSX.CodeBlock & JSXBase.HTMLAttributes<HTMLCodeBlockElement>;
            "component-sidebar": LocalJSX.ComponentSidebar & JSXBase.HTMLAttributes<HTMLComponentSidebarElement>;
            "doc-usage": LocalJSX.DocUsage & JSXBase.HTMLAttributes<HTMLDocUsageElement>;
            "hl-code": LocalJSX.HlCode & JSXBase.HTMLAttributes<HTMLHlCodeElement>;
            "page-components": LocalJSX.PageComponents & JSXBase.HTMLAttributes<HTMLPageComponentsElement>;
            "page-helper-classes": LocalJSX.PageHelperClasses & JSXBase.HTMLAttributes<HTMLPageHelperClassesElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-notfound": LocalJSX.PageNotfound & JSXBase.HTMLAttributes<HTMLPageNotfoundElement>;
            "page-standard": LocalJSX.PageStandard & JSXBase.HTMLAttributes<HTMLPageStandardElement>;
            "theme-setter": LocalJSX.ThemeSetter & JSXBase.HTMLAttributes<HTMLThemeSetterElement>;
            "utterances-div": LocalJSX.UtterancesDiv & JSXBase.HTMLAttributes<HTMLUtterancesDivElement>;
        }
    }
}
