import { Component, Host, h, Prop } from '@stencil/core';

@Component({
  tag: 'codepen-link',
  styleUrl: 'codepen-link.scss',
})
export class CodepenLink {
  /**
   * JSON options defined here:
   * https://blog.codepen.io/documentation/prefill/
   */
  /**
   * Title of new pen
   */
  @Prop() penTitle?: string = 'New Pen';

  /**
   * Description of new pen
   */
  @Prop() description?: string = '';

  /**
   * When the Pen is saved, it will save as Private if logged in user has that privledge, otherwise it will save as public
   */
  @Prop() isPrivate?: boolean = false;

  /**
   * If supplied, the Pen will save as a fork of this id. Note it's not the slug, but ID. You can find the ID of a Pen with `window.CP.pen.id` in the browser console.
   */
  @Prop() parent?: string = '';

  /**
   * an array of strings
   */
  @Prop() tags?: Array<string> = [];

  /**
   * Set which editors are open. In this example HTML open, CSS closed, JS open
   */
  @Prop() editors?: string = '111';

  @Prop() layout?: 'top' | 'left' | 'right' = 'top';

  @Prop() html?: string = '<p>Generated by &lt;codepen-link&gt;</p>';
  @Prop() html_pre_processor?: 'none' | 'slim' | 'haml' | 'markdown' = 'none';
  @Prop() css?: string = '';
  @Prop() css_pre_processor?: 'none' | 'less' | 'scss' | 'sass' | 'stylus' = 'none';
  @Prop() css_starter?: 'normalize' | 'reset' | 'neither' = 'neither';
  @Prop() css_prefix?: 'autoprefixer' | 'prefixfree' | 'neither' = 'neither';
  @Prop() js?: string = '';
  @Prop() js_pre_processor?: 'none' | 'coffeescript' | 'babel' | 'livescript' | 'typescript' = 'none';

  @Prop() html_classes?: string = '';

  @Prop() head?: string = '';
  /**
   * semi-colon separate multiple files
   */
  @Prop() css_external?: string = '';
  /**
   * semi-colon separate multiple files
   */
  @Prop() js_external?: string = '';

  render() {
    const {
      penTitle: title,
      description,
      isPrivate,
      parent,
      tags,
      editors,
      layout,
      html,
      css,
      css_starter,
      css_prefix,
      js,
      js_pre_processor,
      html_classes,
      head,
      css_external,
      js_external,
    } = this;

    const data = JSON.stringify({
      title,
      description,
      isPrivate,
      parent,
      tags,
      editors,
      layout,
      html,
      css,
      css_starter,
      css_prefix,
      js,
      js_pre_processor,
      html_classes,
      head,
      css_external,
      js_external,
    });

    return (
      <Host>
        <form action="https://codepen.io/pen/define" method="POST" target="_blank">
          <input type="hidden" name="data" value={data} />

          <div class="submit-wrapper">
            <button type="submit"></button>
            <slot></slot>
          </div>
        </form>
      </Host>
    );
  }
}
